export default [
  'Norah Jones',
  'Rascal Flatts',
  'Lynyrd Skynyrd',
  'Queens of the Stone Age',
  'Lily Allen',
  'Iggy Azalea',
  'Fleet Foxes',
  'Christina Perri',
  'Fergie',
  'Miguel',
  'Korn',
  'AWOLNATION',
  'Neil Young',
  'Wale',
  'Jason Aldean',
  'Massive Attack',
  'Mike Posner',
  'Tove Lo',
  'Thirty Seconds to Mars',
  'Empire of the Sun',
  'Grouplove',
  'Blur',
  'Gwen Stefani',
  'Nine Inch Nails',
  'ScHoolboy Q',
  'Mary J. Blige',
  'James Blunt',
  'Mark Ronson',
  'Sigur Rós',
  'Black Sabbath',
  'Sean Paul',
  'Vance Joy',
  'The Naked and Famous',
  'Three Days Grace',
  'The Neighbourhood',
  'Meghan Trainor',
  'Keane',
  'Counting Crows',
  'Colbie Caillat',
  'Foals',
  'Feist',
  'Tim McGraw',
  'Van Morrison',
  '3 Doors Down',
  'The Game',
  'Flume',
  'Kiss',
  'Cold War Kids',
  'Gym Class Heroes',
  'Lykke Li',
  'Neon Trees',
  'The Prodigy',
  'Bloc Party',
  'Rise Against',
  'Zac Brown Band',
  'Rod Stewart',
  'Chance the Rapper',
  'All Time Low',
  'Avenged Sevenfold',
  'Jimmy Eat World',
  'Kid Ink',
  'Young the Giant',
  'The 1975',
  'Regina Spektor',
  'Disturbed',
  'Bryan Adams',
  'Keith Urban',
  'Kasabian',
  'Sara Bareilles',
  'Chemical Brothers',
  'Meek Mill',
  'Martin Garrix',
  'La Roux',
  'Beach House',
  'Blake Shelton',
  'Nelly Furtado',
  'Papa Roach',
  'Lenny Kravitz',
  'Iron Maiden',
  'Marilyn Manson',
  'Birdy',
  'Paul McCartney',
  'Sting',
  'James Blake',
  'Sufjan Stevens',
  'No Doubt',
  'Justice',
  'Sean Kingston',
  'Ty Dolla $ign',
  'Tyler, The Creator',
  'The Flaming Lips',
  'Ciara',
  'Miike Snow',
  'Tinie Tempah',
  'Shawn Mendes',
  'Afrojack',
  'Clean Bandit',
  'Ozzy Osbourne',
  'Duran Duran',
  'Sublime',
  'Leona Lewis',
  'Brad Paisley',
  'G-Eazy',
  'Aretha Franklin',
  'Juicy J',
  'NERO',
  'Gavin DeGraw',
  '3OH!3',
  'The Wanted',
  'Van Halen',
  'Diplo',
  'Fetty Wap',
  'Bring Me The Horizon',
  'Grizzly Bear',
  'Cee Lo Green',
  'Olly Murs',
  'Interpol',
  'Kenny Chesney',
  'Kygo',
  'The Cranberries',
  'Robbie Williams',
  'Jeezy',
  'Björk',
  'Lifehouse',
  'Def Leppard',
  'Metric',
  'Blondie',
  'Gucci Mane',
  'Fatboy Slim',
  'Waka Flocka Flame',
  'Glee Cast',
  'Alabama Shakes',
  'Hot Chip',
  'Sum 41',
  'Alice In Chains',
  'Damien Rice',
  'Walk the Moon',
  'The Verve',
  'Earth, Wind & Fire',
  'Tegan and Sara',
  'Aloe Blacc',
  'HAIM',
  'Ice Cube',
  '5 Seconds of Summer',
  'Busta Rhymes',
  'French Montana',
  'Ben Howard',
  'Alanis Morissette',
  'A Day to Remember',
  'Kaiser Chiefs',
  'Backstreet Boys',
  'DJ Snake',
  'New Order',
  'Limp Bizkit',
  'The Band Perry',
  'Emeli Sandé',
  'Soundgarden',
  'Wilco',
  'CHVRCHES',
  'Local Natives',
  'Common',
  'Travis Scott',
  'Breaking Benjamin',
  'Matchbox Twenty',
  'Beirut',
  'Rae Sremmurd',
  'Paul Simon',
  'Spoon',
  'Armin van Buuren',
  'Far East Movement',
  'Steve Aoki',
  'Icona Pop',
  'Phantogram',
  'Crystal Castles',
  'Mika',
  'Jamiroquai',
  'The Roots',
  'Placebo',
  'Wu-Tang Clan',
  'Santigold',
  'Miranda Lambert',
  'José González',
  'Migos',
  'Gnarls Barkley',
  'Celine Dion',
  'Good Charlotte',
  'A Tribe Called Quest',
  'ZZ Top',
  'LMFAO',
  'Sheryl Crow',
  'Fifth Harmony',
  'Benny Benassi',
  'Jack White',
  'Daughtry',
  'Florida Georgia Line',
  'Bombay Bicycle Club',
  'Simple Plan',
  'The Pussycat Dolls',
  'Capital Cities',
  'Erykah Badu',
  'Paolo Nutini',
  'The Decemberists',
  'Belle and Sebastian',
  'Shinedown',
  'Angus & Julia Stone',
  'TV On the Radio',
  'Natasha Bedingfield',
  'Little Mix',
  'Bonobo',
  'Cake',
  'My Chemical Romance',
  'Deep Purple',
  'Ray LaMontagne',
  'Foreigner',
  'Young Thug',
  'Ingrid Michaelson',
  'Broken Bells',
  'Dido',
  'YG',
  'Kylie Minogue',
  'The Ting Tings',
  'Cobra Starship',
  'Prince',
  'Missy Elliott',
  'Portishead',
  'Jay Sean',
  'Peter Bjorn and John',
  'Air',
  'Bullet for My Valentine',
  'Third Eye Blind',
  'Seether',
  'Bright Eyes',
  'Ratatat',
  'James Taylor',
  'Deftones',
  'Pusha T',
  'Halsey',
  'Fabolous',
  'Animal Collective',
  'Cat Power',
  'Kaskade',
  'Marina and the Diamonds',
  'Boston',
  'Milky Chance',
  'Sade',
  'Charli XCX',
  'DMX',
  'MØ',
  'Keri Hilson',
  'Portugal. The Man',
  'Kelly Rowland',
  'Boys Like Girls',
  'The Head and the Heart',
  'Ben Harper',
  'Matt and Kim',
  'Bee Gees',
  'Sarah McLachlan',
  'The Wombats',
  'Al Green',
  'City and Colour',
  'BASSNECTAR',
  'Bill Withers',
  'Eric Church',
  'Robyn',
  'Stone Temple Pilots',
  'Alice Cooper',
  'The Avett Brothers',
  'Alex Clare',
  'Fitz & The Tantrums',
  'Rudimental',
  'Shaggy',
  'Tracy Chapman',
  'Rage Against The Machine',
  'Tool',
  'Röyksopp',
  'Lil Jon',
  'James Bay',
  'James Morrison',
  'Daughter',
  'The Temptations',
  'Toby Keith',
  'Billy Idol',
  'John Newman',
  'Stereophonics',
  'My Morning Jacket',
  'The Lonely Island',
  'Grimes',
  'Ryan Adams',
  'Example',
  'Cypress Hill',
  'Nick Jonas',
  'Lionel Richie',
  'Kid Rock',
  'TLC',
  'Rammstein',
  'George Ezra',
  'Alesso',
  'SBTRKT',
  'Scorpions',
  'Jamie Foxx',
  'Steve Miller Band',
  'London Grammar',
  'Cyndi Lauper',
  'Pendulum',
  'Mayday Parade',
  'Yellowcard',
  'Logic',
  'Boyz II Men',
  'Magic!',
  'Cascada',
  'Silversun Pickups',
  'Five Finger Death Punch',
  'Labrinth',
  'Sleeping With Sirens',
  'Washed Out',
  'Little Dragon',
  'Tears For Fears',
  'The Vaccines',
  'Iggy Pop',
  'BANKS',
  'Jhené Aiko',
  'Flux Pavilion',
  'Peter Gabriel',
  'The Civil Wars',
  'Switchfoot',
  'Metronomy',
  'Pretty Lights',
  'A$AP Ferg',
  'PSY',
  'Fugees',
  'Chromeo',
  'Andrew Bird',
  'Wolfmother',
  'Phillip Phillips',
  'Editors',
  'Kelis',
  'Mötley Crüe',
  'Jake Bugg',
  'Imogen Heap',
  'Bush',
  'Duffy',
  'Jordin Sparks',
  'Pantera',
  'David Gray',
  'Megadeth',
  'The Raconteurs',
  'Caribou',
  'Taking Back Sunday',
  'Dierks Bentley',
  'Hardwell',
  'The Fratellis',
  'Staind',
  'ODESZA',
  'Daryl Hall & John Oates',
  'Rita Ora',
  'David Bowie',
  'OK Go',
  'Eddie Vedder',
  'Tom Waits',
  'Hunter Hayes',
  'Toro Y Moi',
  'Daddy Yankee',
  'Cut Copy',
  'Creed',
  'Estelle',
  'Adam Lambert',
  'Willie Nelson',
  'Heart',
  'George Michael',
  'Mos Def',
  'Garbage',
  'Matt Nathanson',
  'Rush',
  'Janet Jackson',
  'Bryson Tiller',
  'Tenacious D',
  'Charlie Puth',
  'Chiddy Bang',
  'Toto',
  'Iyaz',
  'Rob Zombie',
  'Biffy Clyro',
  'INXS',
  'Elbow',
  'Audioslave',
  'We The Kings',
  'Plan B',
  '311',
  'Matisyahu',
  'Travie McCoy',
  'Purity Ring',
  'Flying Lotus',
  'George Strait',
  'Post Malone',
  'Asking Alexandria',
  'Goldfrapp',
  'Jonas Brothers',
  'Hoobastank',
  'PJ Harvey',
  'Young Money',
  'Kodaline',
  'St. Vincent',
  'Tom Petty',
  'Cher Lloyd',
  'Explosions in the Sky',
  'Alessia Cara',
  'AlunaGeorge',
  'Corinne Bailey Rae',
  'ZAYN',
  'N.W.A.',
  'Yeasayer',
  'KT Tunstall',
  'The Used',
  'Dixie Chicks',
  'Knife Party',
  'Pierce the Veil',
  'Scissor Sisters',
  'Porter Robinson',
  'Hans Zimmer',
  'Macklemore',
  'Chicago',
  'Dizzee Rascal',
  'Darius Rucker',
  'Sleigh Bells',
  'Kansas',
  'Dropkick Murphys',
  'Groove Armada',
  'Janelle Monáe',
  'Ms. Lauryn Hill',
  'LL Cool J',
  'Eels',
  'Kool & The Gang',
  'PartyNextDoor',
  'Phil Collins',
  'Metro Station',
  'The Drums',
  'Glass Animals',
  'E-40',
  'The Kills',
  'Broken Social Scene',
  'Galantis',
  'The Stone Roses',
  'Flight Facilities',
  'Sage the Gemini',
  'Seal',
  'Brand New',
  'Martin Solveig',
  'Basement Jaxx',
  'Tom Odell',
  'Hollywood Undead',
  'Thievery Corporation',
  'Cheap Trick',
  'The Postal Service',
  'Barenaked Ladies',
  'The Cars',
  'Allman Brothers Band',
  'a-ha',
  'Skillet',
  'of Montreal',
  'She & Him',
  'Chase & Status',
  'Atmosphere',
  'Rich Homie Quan',
  'Doobie Brothers',
  'Stromae',
  'Joey Bada$$',
  'Yo Gotti',
  'Shania Twain',
  'Jessie Ware',
  'Hot Chelle Rae',
  'Mogwai',
  'The Isley Brothers',
  'Fiona Apple',
  'Take That',
  'Jess Glynne',
  'Sugarland',
  'The Hives',
  'Best Coast',
  'Tinashe',
  'Naughty Boy',
  'Dillon Francis',
  'Godsmack',
  'Tech N9ne',
  'Dashboard Confessional',
  'Talib Kweli',
  'Nico & Vinz',
  'First Aid Kit',
  'Elvis Costello',
  'Simple Minds',
  'Blue Öyster Cult',
  'Survivor',
  'Stone Sour',
  'New Boyz',
  'Enya',
  'N.E.R.D.',
  'Puddle of Mudd',
  'Jesse McCartney',
  'The Cardigans',
  'Billy Currington',
  'Wyclef Jean',
  'AFI',
  'Pet Shop Boys',
  'Hinder',
  'Leonard Cohen',
  'American Authors',
  'Neil Diamond',
  'Andy Grammer',
  'Skylar Grey',
  'Dolly Parton',
  'Styx',
  'A Perfect Circle',
  'Smash Mouth',
  'UB40',
  'Noah & The Whale',
  'Chevelle',
  'Mário',
  'Eric Prydz',
  'Jake Owen',
  'Don Omar',
  'Machine Gun Kelly',
  'DJ Shadow',
  'Kate Nash',
  'Friendly Fires',
  'Wham!',
  'Omarion',
  'Faith No More',
  'Travis',
  'Neon Indian',
  'Morrissey',
  'Little Big Town',
  'Robin Schulz',
  'Bad Meets Evil',
  'Cher',
  'Mac DeMarco',
  'Deerhunter',
  'The Animals',
  'Gossip',
  'Zero 7',
  'Fort Minor',
  'Public Enemy',
  'Krewella',
  'Real Estate',
  'Ginuwine',
  'Bat For Lashes',
  'Escape the Fate',
  'Violent Femmes',
  'Jet',
  'Jamie xx',
  'Of Mice & Men',
  'Dev',
  'Flyleaf',
  'Supertramp',
  'Killswitch Engage',
  'Bone Thugs-n-Harmony',
  'Slayer',
  'Never Shout Never',
  'Buckcherry',
  'Bowling for Soup',
  'Jennifer Hudson',
  'Alan Jackson',
  'Pretenders',
  'X Ambassadors',
  'Lee Brice',
  'The Bravery',
  'Aphex Twin',
  'Judas Priest',
  'Live',
  'Poison',
  'Ben Folds',
  'Keyshia Cole',
  'Danny Brown',
  'Duck Sauce',
  'Whitesnake',
  'Slightly Stoopid',
  'The Pretty Reckless',
  'De La Soul',
  'The Dandy Warhols',
  'Maxwell',
  'Rufus Wainwright',
  'Echosmith',
  'The Libertines',
  'Years & Years',
  'DJ Fresh',
  'Lloyd',
  'Collective Soul',
  'Chuck Berry',
  'Lil Uzi Vert',
  'Zara Larsson',
  'Five For Fighting',
  'Mr. Scruff',
  'Theory of a Deadman',
  'Will Smith',
  'Cheryl',
  'Chief Keef',
  'Citizen Cope',
  'Earl Sweatshirt',
  'Ja Rule',
  'REO Speedwagon',
  'You Me At Six',
  'Mat Kearney',
  'Pat Benatar',
  'Jill Scott',
  'Mr Probz',
  'Troye Sivan',
  'Faithless',
  'Bloodhound Gang',
  'Tina Turner',
  'Cults',
  'Ricky Martin',
  'D12',
  'Alexandra Stan',
  'Annie Lennox',
  'Chris Young',
  'Steely Dan',
  'Pulp',
  'Warpaint',
  'White Lies',
  'Breathe Carolina',
  'Rusko',
  'Secondhand Serenade',
  'STRFKR',
  'Craig David',
  'James Arthur',
  'Faith Hill',
  'Laura Marling',
  'Tori Amos',
  'New Found Glory',
  'Bebe Rexha',
  'Soulja Boy',
  'Devendra Banhart',
  'Eli Young Band',
  'Azealia Banks',
  'Diana Ross',
  'The Cinematic Orchestra',
  'Kenny Loggins',
  'Bad Religion',
  'Simon & Garfunkel',
  'Duke Dumont',
  'Joss Stone',
  'Meat Loaf',
  'The Commodores',
  'Rob Thomas',
  'The War on Drugs',
  'Brandy',
  'The-Dream',
  'Hellogoodbye',
  'LCD Soundsystem',
  'Yo La Tengo',
  'Bingo Players',
  'Band of Skulls',
  'The Black Crowes',
  'Joshua Radin',
  'OMI',
  'Kevin Gates',
  'Slash',
  'Everclear',
  'Hoodie Allen',
  'Atlas Genius',
  'Echo & The Bunnymen',
  'Primal Scream',
  'Dada Life',
  'Relient K',
  'Fat Joe',
  'Joe Cocker',
  'The Veronicas',
  'Kurt Vile',
  'Yes',
  'Manu Chao',
  'Karmin',
  'Stevie Nicks',
  'Stars',
  'Europe',
  'Mazzy Star',
  'O.A.R.',
  'Dr. Dog',
  'Manic Street Preachers',
  'Baby Bash',
  'Basshunter',
  'Melanie Martinez',
  'Kings of Convenience',
  'Ra Ra Riot',
  'Die Antwoord',
  'Asher Roth',
  'Rjd2',
  'The Human League',
  'Underworld',
  'Razorlight',
  'Finger Eleven',
  'Kimbra',
  'Marc Anthony',
  'Parachute',
  'John Mellencamp',
  'Method Man',
  'Ace Hood',
  'Above & Beyond',
  'Nicole Scherzinger',
  'Doves',
  'Blind Melon',
  'John Williams',
  'P.O.D.',
  'August Alsina',
  'Brantley Gilbert',
  'Ludovico Einaudi',
  'Pentatonix',
  'Tycho',
  'Crowded House',
  'Future Islands',
  'Ashanti',
  'Sam Hunt',
  'Josh Turner',
  'Toni Braxton',
  'Tory Lanez',
  'Herbie Hancock',
  'Klaxons',
  'Prince Royce',
  'Kehlani',
  'Birdman',
  'House of Pain',
  'Paloma Faith',
  'Thom Yorke',
  'Father John Misty',
  'Baauer',
  'Axwell',
  'The Knife',
  'Four Tet',
  'Black Veil Brides',
  'Madness',
  'Flogging Molly',
  'Amos Lee',
  'Kavinsky',
  'Augustana',
  'The Streets',
  'Daniel Powter',
  'Coheed and Cambria',
  'JoJo',
  'Dirty Heads',
  'Desiigner',
  'Jewel',
  'Blackstreet',
  'Coolio',
  'Hilary Duff',
  'The Darkness',
  'The Vamps',
  'Vanessa Carlton',
  'Lamb of God',
  'Foxes',
  'Mobb Deep',
  'Men At Work',
  'Angels And Airwaves',
  'The Ready Set',
  'Jurassic 5',
  'The Maine',
  'Uncle Kracker',
  'The Glitch Mob',
  'Don McLean',
  'Twista',
  'America',
  'Austin Mahone',
  'Crystal Fighters',
  'Lil Yachty',
  'The Cult',
  'Beastie Boys',
  'Lukas Graham',
  'Boyce Avenue',
  'Drowning Pool',
  'Mana',
  'Jimmy Buffett',
  'Royal Blood',
  'Action Bronson',
  'Deorro',
  'Bad Company',
  'The Maccabees',
  'Jackson Browne',
  'Zeds Dead',
  'Anthony Hamilton',
  'Dexys Midnight Runners',
  'Thomas Rhett',
  'Bonnie Tyler',
  'Hillsong United',
  'Flight of the Conchords',
  'Social Distortion',
  'Katy B',
  'Coldplay',
  'Rihanna',
  'U2',
  'Eminem',
  'Maroon 5',
  'Adele',
  'Drake',
  'Kanye West',
  'Bruno Mars',
  'Katy Perry',
  'Beyoncé',
  'Red Hot Chili Peppers',
  'Lady Gaga',
  'Kings of Leon',
  'Lil Wayne',
  'Chris Brown',
  'The Killers',
  'Calvin Harris',
  'Ed Sheeran',
  'Radiohead',
  'David Guetta',
  'Justin Timberlake',
  'Taylor Swift',
  'Justin Bieber',
  'Usher',
  'Mumford & Sons',
  'Muse',
  'Imagine Dragons',
  'Ellie Goulding',
  'Nicki Minaj',
  'Wiz Khalifa',
  'The Weeknd',
  'Black Eyed Peas',
  'Lana Del Rey',
  'Green Day',
  'Foo Fighters',
  'Kendrick Lamar',
  'Pitbull',
  'Linkin Park',
  'Flo Rida',
  'The Rolling Stones',
  'Arctic Monkeys',
  'Avicii',
  'OneRepublic',
  'The Black Keys',
  'Jason Derulo',
  'Metallica',
  'Fall Out Boy',
  'Alicia Keys',
  'Kid Cudi',
  'MGMT',
  'Paramore',
  'Britney Spears',
  'The xx',
  'Skrillex',
  'Foster the People',
  'Queen',
  'Daft Punk',
  'John Mayer',
  'John Legend',
  'Miley Cyrus',
  'Kesha',
  'Arcade Fire',
  'Gorillaz',
  'T.I.',
  'Shakira',
  'Jason Mraz',
  'Snoop Dogg',
  'Bon Iver',
  'Train',
  'Big Sean',
  'J. Cole',
  'Sia',
  'One Direction',
  'blink-182',
  'Lorde',
  'Pearl Jam',
  'Jack Johnson',
  'Elton John',
  'Nickelback',
  'Bob Dylan',
  'AC/DC',
  'The Cure',
  'Fleetwood Mac',
  'B.o.B',
  'Enrique Iglesias',
  'Trey Songz',
  'Bastille',
  'Weezer',
  'Ariana Grande',
  'A$AP Rocky',
  'The Fray',
  'Aerosmith',
  'The Lumineers',
  'The Strokes',
  'Death Cab for Cutie',
  'Jay-Z',
  'Kelly Clarkson',
  'Of Monsters and Men',
  'Madonna',
  'Ne-Yo',
  'Dr. Dre',
  'Vampire Weekend',
  'Panic! At the Disco',
  'Bon Jovi',
  'The Script',
  '50 Cent',
  'Avril Lavigne',
  'Major Lazer',
  'Two Door Cinema Club',
  'Demi Lovato',
  'Jennifer Lopez',
  'Phoenix',
  'Jessie J',
  'Mariah Carey',
  'Fun.',
  'Beck',
  'M83',
  'The Kooks',
  'Tyga',
  'Pharrell Williams',
  'Sam Smith',
  'Michael Bublé',
  'Frank Ocean',
  'Snow Patrol',
  'Deadmau5',
  'Christina Aguilera',
  'alt-J',
  'Passion Pit',
  'Gotye',
  'Nelly',
  'Florence and the Machine',
  'Akon',
  'OutKast',
  'Ludacris',
  'Journey',
  'Lady Antebellum',
  'Stevie Wonder',
  'Eric Clapton',
  'Lupe Fiasco',
  'Modest Mouse',
  'System of a Down',
  'Twenty One Pilots',
  'Bruce Springsteen',
  'Future',
  'Disclosure',
  'The Who',
  'Smashing Pumpkins',
  'Childish Gambino',
  'Mac Miller',
  'Depeche Mode',
  'Band of Horses',
  'M.I.A.',
  'Cage the Elephant',
  'The Goo Goo Dolls',
  'Zedd',
  'Billy Joel',
  'Hozier',
  'Franz Ferdinand',
  'The Offspring',
  'Pixies',
  '2 Chainz',
  'Selena Gomez',
  'Eagles',
  'DJ Khaled',
  'Yeah Yeah Yeahs',
  'Rick Ross',
  'Nas',
  'The Shins',
  'T-Pain',
  'The National',
  'Tiësto',
  'The Beach Boys',
  'Carly Rae Jepsen',
  'Swedish House Mafia',
  'Incubus',
  'R. Kelly',
  'Tame Impala',
  'Owl City',
  'Taio Cruz',
  'Evanescence',
  'Jeremih',
  'Robin Thicke',
  'Timbaland',
  'Iron & Wine',
  'Moby',
  'Passenger',
  'Pink',
  'Luke Bryan',
  'Carrie Underwood',
  'The All-American Rejects',
  'Santana',
  'The Temper Trap',
  'Dave Matthews Band',
  'will.i.am',
  'Slipknot',
  'The Chainsmokers',
];
